// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

// KV is an autogenerated mock type for the KV type
type KV struct {
	mock.Mock
}

// Get provides a mock function with given fields: path, token
func (_m *KV) Get(path string, token string) (map[string]string, error) {
	ret := _m.Called(path, token)

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func(string, string) map[string]string); ok {
		r0 = rf(path, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(path, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
